In [4]:
# Import numpy
import numpy as np

# Create a numpy array from height_in: np_height_in
baseball = [180, 215, 210, 210, 188, 176, 209, 200]
np_height_in = np.array(baseball)

# Print out np_height_in
print(np_height_in)

# Convert np_height_in to m: np_height_m
np_height_m = np_height_in * 0.0254

# Print np_height_m
print(np_height_m)

[180 215 210 210 188 176 209 200]
[4.572  5.461  5.334  5.334  4.7752 4.4704 5.3086 5.08  ]


In [6]:
# slicing
print(np_height_m[2:])

[5.334  5.334  4.7752 4.4704 5.3086 5.08  ]


In [7]:
# 2d array
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

import numpy as np

np_baseball = np.array(baseball)
print(type(np_baseball))
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


In [8]:
# 2d arithmetic

conversion = np.array([2, 4])

print(np_baseball * conversion) # rows = columns

[[360.  313.6]
 [430.  410.8]
 [420.  394. ]
 [376.  300.8]]


In [14]:
# functions

print(np.mean(np_baseball))

print(np.median(np_baseball))

print(np.std(np_baseball))

print(np.corrcoef(np_baseball[:,0], np_baseball[:,1]))

143.475
141.35
56.390973346804365
[[1.         0.95865738]
 [0.95865738 1.        ]]
